name: dacsslide
version: 0.3.0-beta+2
environment:
  sdk: '>=1.13.0 <=2.0.0'
author: Valentyn Shybanov <olostan@gmail.com>
description: Dart CSS presentation framework
homepage: https://github.com/olostan/dacsslide
dependencies:
  angular: "^5.0.0-alpha"
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.2
  test: '>0.12.0 <1.0.0'
  http: '>0.10.0 <1.0.0'
  resource: '>=2.1.2 < 3.0.0'
  path: '>1.4.0 < 2.0.0'
  args: '^1.2.0'
  build_config: '^0.2.6+1'
  build: "^0.12.6"
dev_dependencies:
  sass_builder: ^2.0.0
  build_runner: ^0.8.2
  build_web_compilers: '>=0.3.6 <0.5.0'
