name: dacsslide
version: 0.0.13
author: Valentyn Shybanov <olostan@gmail.com>
description: Dart CSS presentation framework.
homepage: https://github.com/olostan/dacsslide
dependencies:
  angular: '>=1.0.0 <1.5.0'
  browser: '>=0.9.1 <1.0.0'
  csslib_transform: '>=0.0.1 <0.1.0'
  test: '>=0.11.0 <0.13.0'
transformers:
- angular:
    html_files:
    - lib/presentation.html
- $dart2js:
    commandLineOptions:
    - --trust-type-annotations
    minify: true
- dacsslide
- csslib_transform
