name: dacsslide
version: 0.3.0-beta
environment:
  sdk: '>=1.13.0 <=2.0.0'
author: Valentyn Shybanov <olostan@gmail.com>
description: Dart CSS presentation framework
homepage: https://github.com/olostan/dacsslide
dependencies:
  angular: "^5.0.0-alpha"
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.2
  csslib_transform: '>=0.0.1 <0.1.0'
  test: '>0.12.0 <1.0.0'
  http: '>0.10.0 <1.0.0'
  barback: '>0.10.0 < 1.0.0'
  resource: '>=2.1.2 < 3.0.0'
  path: '>1.4.0 < 2.0.0'
  args: '^1.2.0'
transformers:
- dacsslide
- csslib_transform
- angular:
    entry_points:
    - web/main.dart
- dart_to_js_script_rewriter

web:
  compiler:
    debug: dartdevc
